#!/usr/bin/env python3
import subprocess


def main(args):
	
	baud_index = 0
	arduino_nano = False
	for arg_index in range(len(args)):
		if args[arg_index].startswith("-b"):
			baud_index = arg_index
		if args[arg_index] == "-patmega328p":
			arduino_nano = True
	
	if arduino_nano:
		args[baud_index] = "-b57600"
	
	args[0] += ".real"
	subprocess.call(args)
	
	return 0


if __name__ == '__main__':
	import sys
	sys.exit(main(sys.argv))
